import { AutomationDefinitionSchema, SchemaVersion } from "../protocol/schemas.js";

const AUTHENTICATED = {
  id: "authenticated",
  description: "The dedicated browser profile is authenticated.",
  source: "runtime",
  path: "session.authenticated",
  operator: "equals",
  expected: true,
  required: true,
};

const ACCOUNT_MATCHES = {
  id: "account_matches",
  description: "The visible account and shop match the requested target.",
  source: "page",
  path: "identity.matchesTarget",
  operator: "equals",
  expected: true,
  required: true,
};

const NO_CHALLENGE = {
  id: "no_challenge",
  description: "No captcha, verification challenge, or permission wall is present.",
  source: "page",
  path: "page.challengeDetected",
  operator: "equals",
  expected: false,
  required: true,
};

const TARGET_ENTITY_MATCHES = {
  id: "target_entity_matches",
  description: "The page entity identifier matches the requested entity.",
  source: "page",
  path: "entity.matchesTarget",
  operator: "equals",
  expected: true,
  required: true,
};

const READ_EVIDENCE = [
  "screenshot_before",
  "accessibility_snapshot",
  "visible_text",
  "structured_output",
  "screenshot_after",
];

const WRITE_EVIDENCE = [...READ_EVIDENCE, "execution_receipt"];

function recordsCaptured(entityName) {
  return {
    id: "records_captured",
    description: `${entityName} extraction completed and every record has a source identifier.`,
    source: "extraction",
    path: "summary.recordsValid",
    operator: "equals",
    expected: true,
    required: true,
  };
}

function externalStateConfirmed(description = "The external state reflects the intended action after refresh.") {
  return {
    id: "external_state_confirmed",
    description,
    source: "receipt",
    path: "verification.persistedAfterRefresh",
    operator: "equals",
    expected: true,
    required: true,
  };
}

function definition({
  id,
  label,
  module,
  platform,
  executor = "browser",
  riskLevel = "R1_READ",
  actionType = "EXTRACT",
  entityType,
  description,
  requiredInputs = [],
  allowedMethods = ["click", "extract"],
  observeInstruction,
  extractInstruction,
  verifyInstruction,
  outputSchemaKey,
  preconditions,
  postconditions,
  evidence,
  dailyLimit,
}) {
  return AutomationDefinitionSchema.parse({
    schemaVersion: SchemaVersion,
    id,
    label,
    module,
    platform,
    executor,
    riskLevel,
    actionType,
    entityType,
    description,
    requiredInputs,
    allowedMethods,
    observeInstruction,
    extractInstruction,
    verifyInstruction,
    outputSchemaKey,
    preconditions:
      preconditions ?? (executor === "browser" ? [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE] : []),
    postconditions: postconditions ?? [],
    evidence: evidence ?? (riskLevel.startsWith("R0") ? ["structured_output"] : riskLevel === "R1_READ" ? READ_EVIDENCE : WRITE_EVIDENCE),
    dailyLimit,
    recipeStatus: "catalogued",
  });
}

export const automationTaskCatalog = [
  definition({
    id: "tiktok.orders.sync",
    label: "同步订单列表",
    module: "orders",
    platform: "tiktok_shop",
    entityType: "order_snapshot",
    description: "Read filtered order pages or an official export and return a deduplicated order snapshot.",
    requiredInputs: ["shopId", "statusFilter", "snapshotWindow"],
    allowedMethods: ["click", "selectOption", "extract", "download"],
    observeInstruction: "Locate the Orders area, shop selector, status filter, result count, pagination, and official export control. Do not edit or submit anything.",
    extractInstruction: "Extract visible order identifiers, item or SKU, paid time, order status, fulfillment status, logistics status, tracking identifier, and the active filter context.",
    verifyInstruction: "Verify the active shop and filters, reconcile the visible result count with captured rows or the downloaded file, and confirm that order identifiers are unique.",
    outputSchemaKey: "order_list",
    postconditions: [recordsCaptured("Order")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "tiktok.orders.read_detail",
    label: "读取订单与物流详情",
    module: "orders",
    platform: "tiktok_shop",
    entityType: "order",
    description: "Open one order and capture its authoritative order, deadline, label, and tracking state.",
    requiredInputs: ["shopId", "orderId"],
    observeInstruction: "Locate the order search field, the matching order row, its details entry, logistics timeline, and pickup deadline without changing any field.",
    extractInstruction: "Extract the order ID, shop, items, seller SKU, paid time, pickup deadline, fulfillment status, label status, carrier, tracking ID, and latest logistics event.",
    verifyInstruction: "Confirm the opened order ID equals the requested order ID and all captured logistics facts are visibly supported.",
    outputSchemaKey: "order_detail",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Order detail")],
  }),
  definition({
    id: "tiktok.orders.audit_fulfillment",
    label: "复核未揽收和面单异常",
    module: "orders",
    platform: "tiktok_shop",
    entityType: "order",
    description: "Inspect an order for missing pickup scans, label errors, or fulfillment deadline risk.",
    requiredInputs: ["shopId", "orderId"],
    observeInstruction: "Find the requested order, its shipping label state, carrier tracking timeline, and any fulfillment warning banners. Do not mark the order fulfilled.",
    extractInstruction: "Extract pickup deadline, first carrier scan time, latest scan, label error text, platform warning text, and the facts needed to classify fulfillment risk.",
    verifyInstruction: "Verify all risk conclusions cite visible order or logistics evidence and the order identifier still matches.",
    outputSchemaKey: "fulfillment_audit",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Fulfillment audit")],
  }),
  definition({
    id: "tiktok.orders.send_customer_message",
    label: "发送订单服务消息",
    module: "orders",
    platform: "tiktok_shop",
    riskLevel: "R2_REVERSIBLE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "conversation",
    description: "Send one approved service message in the conversation linked to a specific order.",
    requiredInputs: ["shopId", "orderId", "conversationId", "approvedMessage", "messageHash"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Locate the conversation linked to the requested order, confirm the buyer and order identifiers, inspect recent history for the same message, and locate the composer and send control.",
    verifyInstruction: "After sending, confirm the exact approved message appears once in the correct conversation with a platform timestamp and remains after refresh.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed("The exact message is visible once in the correct order conversation after refresh.")],
    dailyLimit: 50,
  }),
  definition({
    id: "tiktok.orders.send_feedback_request",
    label: "发送中立体验反馈邀请",
    module: "orders",
    platform: "tiktok_shop",
    riskLevel: "R2_REVERSIBLE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "order",
    description: "Send one neutral, policy-checked feedback request after the configured delivery delay.",
    requiredInputs: ["shopId", "orderId", "deliveredAt", "approvedMessage", "messageHash"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Confirm the requested order is delivered, the configured delay has elapsed, no equivalent request exists in history, and locate the correct order conversation.",
    verifyInstruction: "Confirm exactly one neutral feedback request appears in the correct conversation and no incentive or requested rating is present.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed("The neutral request is visible once after refresh and the order remains the requested order.")],
    dailyLimit: 30,
  }),
  definition({
    id: "tiktok.orders.submit_fulfillment",
    label: "提交发货信息",
    module: "orders",
    platform: "tiktok_shop",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "MARK_FULFILLED",
    entityType: "order",
    description: "Submit carrier and tracking details or mark an order fulfilled after a scoped approval grant.",
    requiredInputs: ["shopId", "orderId", "carrier", "trackingId", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "selectOption", "press"],
    observeInstruction: "Locate the requested order fulfillment form, current fulfillment state, carrier selector, tracking input, and final submit control. Do not submit during observation.",
    verifyInstruction: "Confirm the platform shows the requested carrier and tracking ID, fulfillment state changed, an operation timestamp exists, and the state persists after refresh.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 20,
  }),

  definition({
    id: "tiktok.aftersales.sync",
    label: "同步售后工单",
    module: "aftersales",
    platform: "tiktok_shop",
    entityType: "aftersales_snapshot",
    description: "Read open and processing return, refund, cancellation, and dispute cases with deadlines.",
    requiredInputs: ["shopId", "statusFilter", "snapshotWindow"],
    allowedMethods: ["click", "selectOption", "extract", "download"],
    observeInstruction: "Locate Returns, Refunds, Cancellations, or Disputes; identify filters, result counts, pagination, and export controls without changing a case.",
    extractInstruction: "Extract case ID, order ID, type, status, amount, reason, response deadline, appeal deadline, return tracking, and last update time.",
    verifyInstruction: "Reconcile captured cases with the visible result count and confirm every case has a stable identifier and source status.",
    outputSchemaKey: "aftersales_list",
    postconditions: [recordsCaptured("After-sales")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "tiktok.aftersales.read_return_tracking",
    label: "读取退货物流与仓库状态",
    module: "aftersales",
    platform: "tiktok_shop",
    entityType: "aftersales_case",
    description: "Capture the return tracking timeline and current platform decision state for one case.",
    requiredInputs: ["shopId", "caseId", "orderId"],
    observeInstruction: "Open the requested case and locate the return package timeline, tracking identifier, deadline, buyer reason, and platform decision state.",
    extractInstruction: "Extract case ID, order ID, return carrier, tracking ID, latest logistics event, warehouse receipt status, deadlines, and current decision state.",
    verifyInstruction: "Confirm case and order identifiers match the request and all logistics facts are supported by the visible timeline.",
    outputSchemaKey: "aftersales_detail",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Return tracking")],
  }),
  definition({
    id: "tiktok.aftersales.collect_evidence",
    label: "采集售后证据包",
    module: "aftersales",
    platform: "tiktok_shop",
    entityType: "evidence_bundle",
    description: "Collect visible order, logistics, case, and conversation evidence without submitting an appeal.",
    requiredInputs: ["shopId", "caseId", "orderId", "evidenceChecklist"],
    allowedMethods: ["click", "extract", "download"],
    observeInstruction: "Locate each requested evidence source for the case: order facts, tracking, case timeline, buyer reason, and relevant conversation. Do not open a final submission action.",
    extractInstruction: "Return an evidence manifest with source URL pattern, visible timestamp, source entity ID, evidence type, captured facts, and missing checklist items.",
    verifyInstruction: "Confirm every captured artifact is tied to the requested case or order and every missing item is explicitly reported.",
    outputSchemaKey: "evidence_manifest",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Evidence")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "tiktok.aftersales.prepare_appeal",
    label: "填写申诉并停在提交前",
    module: "aftersales",
    platform: "tiktok_shop",
    riskLevel: "R2_REVERSIBLE_WRITE",
    actionType: "TYPE_DRAFT",
    entityType: "aftersales_case",
    description: "Fill an approved appeal draft and attachments, then stop before the final submit action.",
    requiredInputs: ["shopId", "caseId", "approvedDraft", "attachmentManifest"],
    allowedMethods: ["click", "fill", "type", "upload", "selectOption"],
    observeInstruction: "Locate the appeal form, verify the requested case, identify all fields, upload controls, and final submit control. Do not submit.",
    verifyInstruction: "Confirm every field and attachment matches the approved payload, the case ID is correct, and no final submission receipt or state change exists.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [{
      id: "draft_only",
      description: "The approved appeal is fully populated and the final submit action has not fired.",
      source: "receipt",
      path: "verification.draftPreparedWithoutSubmit",
      operator: "equals",
      expected: true,
      required: true,
    }],
    dailyLimit: 20,
  }),
  definition({
    id: "tiktok.aftersales.send_message",
    label: "发送售后服务消息",
    module: "aftersales",
    platform: "tiktok_shop",
    riskLevel: "R2_REVERSIBLE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "aftersales_case",
    description: "Send one approved return-process or evidence-request message for a specific case.",
    requiredInputs: ["shopId", "caseId", "conversationId", "approvedMessage", "messageHash"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Open the conversation linked to the requested case, confirm buyer and case identity, check for a duplicate message, and locate the composer.",
    verifyInstruction: "Confirm the exact approved message appears once in the correct case conversation and persists after refresh.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 40,
  }),
  definition({
    id: "tiktok.aftersales.submit_decision",
    label: "提交退款、拒绝或申诉决定",
    module: "aftersales",
    platform: "tiktok_shop",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "SUBMIT_FORM",
    entityType: "aftersales_case",
    description: "Submit a financially or operationally significant case decision under a scoped grant.",
    requiredInputs: ["shopId", "caseId", "decision", "amount", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "selectOption", "press"],
    observeInstruction: "Open the requested case, verify current state, amount, deadlines, evidence readiness, and the exact final decision control. Do not submit during observation.",
    verifyInstruction: "Confirm the case state, amount, platform reference, and timeline reflect the approved decision and persist after refresh.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 10,
  }),

  definition({
    id: "tiktok.reviews.sync",
    label: "增量同步商品评价",
    module: "reviews",
    platform: "tiktok_shop",
    entityType: "review_snapshot",
    description: "Read Product Ratings with active date, rating, and reply-state filters.",
    requiredInputs: ["shopId", "since", "ratingFilter", "replyFilter"],
    allowedMethods: ["click", "selectOption", "extract", "download"],
    observeInstruction: "Locate Product Ratings, date/rating/reply filters, result count, pagination, and export without opening a reply submission.",
    extractInstruction: "Extract review ID, product or order reference, rating, review text, media metadata, created time, reply status, and active filter context.",
    verifyInstruction: "Reconcile captured reviews with visible counts, confirm review IDs are unique, and retain the active filters and page timestamp.",
    outputSchemaKey: "review_list",
    postconditions: [recordsCaptured("Review")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "tiktok.reviews.read_context",
    label: "读取评价、回复和证据上下文",
    module: "reviews",
    platform: "tiktok_shop",
    entityType: "review",
    description: "Open one review and read its reply state, related conversation, and evidence attachments.",
    requiredInputs: ["shopId", "reviewId"],
    observeInstruction: "Locate the requested review, its existing seller reply, related messages, media attachments, and reply/report controls without submitting anything.",
    extractInstruction: "Extract review ID, rating, text, media metadata, seller reply, latest buyer response, evidence request history, and product/order context.",
    verifyInstruction: "Confirm the review ID matches and every extracted message or attachment is visibly associated with this review or order.",
    outputSchemaKey: "review_detail",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Review context")],
  }),
  definition({
    id: "internal.reviews.prepare_reply",
    label: "生成并合规检查评价回复",
    module: "reviews",
    platform: "internal",
    executor: "internal",
    riskLevel: "R0_INTERNAL",
    actionType: "INTERNAL_COMPUTE",
    entityType: "review",
    description: "Generate a reply from verified facts and block incentives, rating manipulation, or unsupported promises.",
    requiredInputs: ["reviewId", "verifiedFacts", "templateVersion"],
    allowedMethods: [],
    observeInstruction: "No browser observation. Use only verified structured facts supplied by the review ingestion task.",
    verifyInstruction: "Validate the draft against the compliance rules and return facts, draft, risk flags, and confidence as separate fields.",
    outputSchemaKey: "reply_draft",
    postconditions: [recordsCaptured("Reply draft")],
  }),
  definition({
    id: "tiktok.reviews.send_reply",
    label: "发送评价回复",
    module: "reviews",
    platform: "tiktok_shop",
    riskLevel: "R2_REVERSIBLE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "review",
    description: "Send one approved, compliant reply to a specific review.",
    requiredInputs: ["shopId", "reviewId", "approvedReply", "replyHash"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Open the requested review, confirm it is unreplied, inspect for a duplicate text, and locate the reply composer and submit control.",
    verifyInstruction: "Confirm the exact approved reply is visible once on the requested review, reply state changed, and the result persists after refresh.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 30,
  }),
  definition({
    id: "tiktok.reviews.report",
    label: "举报无效评价",
    module: "reviews",
    platform: "tiktok_shop",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "SUBMIT_FORM",
    entityType: "review",
    description: "Submit an invalid-review report with a scoped approval and supporting evidence.",
    requiredInputs: ["shopId", "reviewId", "reasonCode", "evidenceManifest", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "upload", "selectOption", "press"],
    observeInstruction: "Open the requested review report form, verify the review, reason options, evidence controls, and final submit control. Do not submit during observation.",
    verifyInstruction: "Confirm a report state or platform reference ID exists for the requested review and persists after refresh.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 5,
  }),

  definition({
    id: "hcrd.inventory.sync",
    label: "同步惠程荣达库存快照",
    module: "inventory",
    platform: "hcrd",
    entityType: "inventory_snapshot",
    description: "Read all HCRD SKU inventory through the authenticated browser session API, then visually audit a sample with the multimodal model.",
    requiredInputs: ["accountId", "warehouse", "owner", "snapshotWindow"],
    allowedMethods: ["extract"],
    observeInstruction: "Confirm the persistent browser profile has an authenticated HCRD JSESSIONID by requesting one read-only inventory row from the same-origin session API.",
    extractInstruction: "POST to /inventory/inventory/listForClientAction.json with page and rows, paginate to the reported total, preserve the typed source fields, and use the multimodal model to cross-check a small visible sample without changing inventory.",
    verifyInstruction: "Confirm API pagination equals the reported total, every record has seller SKU and warehouse provenance, and the multimodal screenshot sample agrees with the API values.",
    outputSchemaKey: "hcrd_inventory_list",
    postconditions: [recordsCaptured("HCRD inventory")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "hcrd.inventory.sync_in_transit",
    label: "同步惠程荣达在途库存",
    module: "inventory",
    platform: "hcrd",
    entityType: "in_transit_snapshot",
    description: "Read unfinished inbound or replenishment orders and preserve document-level provenance.",
    requiredInputs: ["accountId", "warehouse", "owner", "statusFilter"],
    allowedMethods: ["click", "fill", "selectOption", "extract", "download"],
    observeInstruction: "Locate unfinished inbound or replenishment records, status filters, document details, pagination, and export without editing a document.",
    extractInstruction: "Extract inbound document ID, seller SKU, expected quantity, received quantity, remaining quantity, status, expected date, and last update time.",
    verifyInstruction: "Confirm every in-transit quantity is traceable to a unique unfinished source document and duplicate documents are removed.",
    outputSchemaKey: "in_transit_list",
    postconditions: [recordsCaptured("In-transit")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "tiktok.inventory.sync",
    label: "同步 TikTok SKU 库存",
    module: "inventory",
    platform: "tiktok_shop",
    entityType: "inventory_snapshot",
    description: "Read or download the current seller SKU inventory for a shop.",
    requiredInputs: ["shopId", "snapshotWindow"],
    allowedMethods: ["click", "fill", "selectOption", "extract", "download"],
    observeInstruction: "Locate product or inventory management, active shop, seller SKU search, result count, pagination, and export control without editing stock.",
    extractInstruction: "Extract product ID, seller SKU, variation, platform available stock, listing status, and page update time.",
    verifyInstruction: "Reconcile captured rows or the export with the page count and confirm every row belongs to the requested shop.",
    outputSchemaKey: "inventory_list",
    postconditions: [recordsCaptured("TikTok inventory")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "internal.inventory.reconcile",
    label: "计算库存差异和备货建议",
    module: "inventory",
    platform: "internal",
    executor: "internal",
    riskLevel: "R0_INTERNAL",
    actionType: "INTERNAL_COMPUTE",
    entityType: "inventory_reconciliation",
    description: "Join HCRD, TikTok, in-transit, and safety stock by approved SKU mapping and compute differences.",
    requiredInputs: ["hcrdSnapshotId", "tiktokSnapshotId", "skuMappingVersion", "safetyStockVersion"],
    allowedMethods: [],
    observeInstruction: "No browser observation. Use versioned inventory snapshots and SKU mappings only.",
    verifyInstruction: "Recompute every result and isolate unmapped SKUs; suggested restock must equal max(0, safetyStock - actualStock - inTransit).",
    outputSchemaKey: "inventory_reconciliation",
    postconditions: [recordsCaptured("Inventory reconciliation")],
  }),
  definition({
    id: "tiktok.inventory.prepare_update",
    label: "填写库存调整并停在保存前",
    module: "inventory",
    platform: "tiktok_shop",
    riskLevel: "R2_REVERSIBLE_WRITE",
    actionType: "TYPE_DRAFT",
    entityType: "sku",
    description: "Open the exact seller SKU and populate an approved target stock value without saving.",
    requiredInputs: ["shopId", "sellerSku", "expectedCurrentStock", "targetStock", "adjustmentId"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Locate the exact seller SKU, verify current stock and product identity, locate the stock input and final save control. Do not save.",
    verifyInstruction: "Confirm seller SKU, product, original stock, and populated target stock match the approved adjustment and no save receipt exists.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [{
      id: "inventory_draft_only",
      description: "The target inventory is populated for the correct SKU and has not been saved.",
      source: "receipt",
      path: "verification.inventoryPreparedWithoutSave",
      operator: "equals",
      expected: true,
      required: true,
    }],
    dailyLimit: 50,
  }),
  definition({
    id: "tiktok.inventory.submit_update",
    label: "提交库存调整",
    module: "inventory",
    platform: "tiktok_shop",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "SET_INVENTORY",
    entityType: "sku",
    description: "Persist an approved seller SKU stock change under a scoped approval grant.",
    requiredInputs: ["shopId", "sellerSku", "expectedCurrentStock", "targetStock", "adjustmentId", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Open the exact seller SKU, confirm current stock equals the approved expected value, and locate the final save control. Do not save during observation.",
    verifyInstruction: "Confirm the requested seller SKU displays the target stock after refresh and an operation record or update timestamp exists.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 20,
  }),

  definition({
    id: "echotik.creators.search",
    label: "通过 EchoTik UI 筛选和分页采集达人",
    module: "creators",
    platform: "echotik",
    entityType: "creator_snapshot",
    description: "Apply approved UI filters and capture creator cards through visible pagination or scrolling.",
    requiredInputs: ["searchCriteria", "maxPages", "snapshotWindow"],
    allowedMethods: ["click", "fill", "selectOption", "extract", "download"],
    observeInstruction: "Locate EchoTik creator filters, search control, result count, creator cards, pagination or scrolling, and official export. Use visible UI navigation only.",
    extractInstruction: "Extract creator ID, handle, name, region, follower count, category, email availability flag, recent performance metrics, page number, and active filters.",
    verifyInstruction: "Confirm filters match the requested criteria, creator IDs are unique, captured page boundaries are known, and membership or quota errors are reported.",
    outputSchemaKey: "creator_list",
    postconditions: [recordsCaptured("Creator")],
    evidence: [...READ_EVIDENCE, "download"],
  }),
  definition({
    id: "echotik.creators.read_detail",
    label: "读取达人详情和近期视频",
    module: "creators",
    platform: "echotik",
    entityType: "creator",
    description: "Open one creator and capture authoritative profile, public contact, video, and commerce signals.",
    requiredInputs: ["creatorId"],
    allowedMethods: ["click", "extract", "download"],
    observeInstruction: "Open the requested creator detail and locate profile facts, public contact area, recent videos, performance metrics, and product association evidence.",
    extractInstruction: "Extract creator ID, handle, profile URL, follower metrics, categories, public contact evidence, and the latest ten videos with IDs, dates, views, covers, and product signals.",
    verifyInstruction: "Confirm the detail creator ID matches the request and every video or contact value has a visible source or explicit evidence gap.",
    outputSchemaKey: "creator_detail",
    preconditions: [AUTHENTICATED, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Creator detail")],
  }),
  definition({
    id: "social.creators.collect_public_contact",
    label: "采集达人主页公开联系方式",
    module: "creators",
    platform: "social",
    entityType: "creator_contact",
    description: "Read only contact information that is visibly published on the target creator profile.",
    requiredInputs: ["creatorId", "profileUrl"],
    allowedMethods: ["click", "extract"],
    observeInstruction: "Open the requested public creator profile and locate bio, website, email, and linked social accounts. Do not message, follow, or interact.",
    extractInstruction: "Extract public email or social links with the exact source URL, source text, capture time, and creator identifier.",
    verifyInstruction: "Confirm every contact value is visibly public, belongs to the requested creator, and has source evidence; do not infer hidden contact details.",
    outputSchemaKey: "contact_list",
    preconditions: [NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Public contact")],
  }),
  definition({
    id: "internal.creators.qualify",
    label: "达人归一化和规则筛选",
    module: "creators",
    platform: "internal",
    executor: "internal",
    riskLevel: "R0_INTERNAL",
    actionType: "INTERNAL_COMPUTE",
    entityType: "creator",
    description: "Normalize captured creator evidence, apply versioned qualification rules, and preserve evidence gaps.",
    requiredInputs: ["creatorSnapshotId", "qualificationRuleVersion"],
    allowedMethods: [],
    observeInstruction: "No browser observation. Use only captured creator and video evidence.",
    verifyInstruction: "Recompute the qualification result, keep failed and missing evidence separate, and upsert by stable creator identity.",
    outputSchemaKey: "creator_qualification",
    postconditions: [recordsCaptured("Creator qualification")],
  }),
  definition({
    id: "internal.creators.prepare_outreach",
    label: "生成达人建联草稿",
    module: "creators",
    platform: "internal",
    executor: "internal",
    riskLevel: "R0_INTERNAL",
    actionType: "INTERNAL_COMPUTE",
    entityType: "creator",
    description: "Generate a channel-specific outreach draft from verified creator evidence and a versioned offer template.",
    requiredInputs: ["creatorId", "verifiedEvidence", "offerVersion", "templateVersion"],
    allowedMethods: [],
    observeInstruction: "No browser observation. Use verified creator evidence and approved offer facts only.",
    verifyInstruction: "Return the draft, channel, evidence citations, unsupported-claim flags, and content hash as separate fields.",
    outputSchemaKey: "outreach_draft",
    postconditions: [recordsCaptured("Outreach draft")],
  }),
  definition({
    id: "mail.creators.send_outreach",
    label: "发送单封达人邮件",
    module: "creators",
    platform: "mail",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "creator",
    description: "Send one approved outreach email through the formal outbox or a verified mail UI recipe.",
    requiredInputs: ["creatorId", "recipient", "subject", "approvedBody", "outboxId", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Confirm the target mailbox, recipient, no active suppression or cooldown, no duplicate outbox message, and locate compose controls. Do not send during observation.",
    verifyInstruction: "Confirm one Sent message exists with the requested recipient, subject, body hash, thread ID, and send time; persist the provider or thread reference.",
    preconditions: [AUTHENTICATED, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 20,
  }),
  definition({
    id: "social.creators.send_outreach",
    label: "发送单条达人社媒建联消息",
    module: "creators",
    platform: "social",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "creator",
    description: "Send one approved social outreach message after identity, cooldown, and duplicate checks.",
    requiredInputs: ["creatorId", "profileUrl", "approvedMessage", "messageHash", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Confirm the requested creator profile, existing conversation, cooldown and suppression state, duplicate history, and message composer. Do not send during observation.",
    verifyInstruction: "Confirm the exact message appears once in the correct creator conversation with a platform timestamp and persists after refresh.",
    preconditions: [AUTHENTICATED, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 10,
  }),
  definition({
    id: "mail.creators.sync_replies",
    label: "同步达人邮件回复",
    module: "creators",
    platform: "mail",
    entityType: "creator_reply_snapshot",
    description: "Read new replies by thread and associate them with a creator and outreach record.",
    requiredInputs: ["mailboxId", "sinceCursor"],
    allowedMethods: ["click", "extract"],
    observeInstruction: "Locate new inbound mail since the cursor, thread identifiers, sender, recipient, timestamps, labels, and prior sent outreach. Do not reply or relabel.",
    extractInstruction: "Extract message ID, thread ID, sender, recipients, subject, received time, body text, automated-response indicators, and associated outreach identifiers.",
    verifyInstruction: "Confirm messages are newer than the cursor, unique by provider message ID, and correctly associated by thread before CRM updates.",
    outputSchemaKey: "mail_reply_list",
    postconditions: [recordsCaptured("Mail reply")],
  }),
  definition({
    id: "mail.creators.send_followup",
    label: "发送达人跟进邮件",
    module: "creators",
    platform: "mail",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "creator",
    description: "Send one approved follow-up in the original thread after reply, cooldown, and attempt-limit checks.",
    requiredInputs: ["creatorId", "threadId", "approvedBody", "outboxId", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Open the original thread, confirm no human reply exists, cooldown elapsed, attempt limit not exceeded, and locate Reply. Do not send during observation.",
    verifyInstruction: "Confirm one new message exists in the original thread with the approved body hash and timestamp, without creating a duplicate thread.",
    preconditions: [AUTHENTICATED, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 10,
  }),

  definition({
    id: "tiktok.messages.sync",
    label: "同步客服待办会话",
    module: "messages",
    platform: "tiktok_shop",
    entityType: "conversation_snapshot",
    description: "Read unread, unreplied, due-soon, and overdue customer conversations.",
    requiredInputs: ["shopId", "statusFilter", "sinceCursor"],
    allowedMethods: ["click", "selectOption", "extract"],
    observeInstruction: "Locate Customer Messages, requested status filters, operation hours context, conversation result count, and pagination without changing a conversation.",
    extractInstruction: "Extract conversation ID, buyer alias, linked order, last message time and preview, unread/unreplied state, due time, and category.",
    verifyInstruction: "Reconcile captured conversations with visible counts and confirm every conversation has a stable ID, timestamp, and shop context.",
    outputSchemaKey: "message_list",
    postconditions: [recordsCaptured("Conversation")],
  }),
  definition({
    id: "tiktok.messages.read_context",
    label: "读取客服会话和订单上下文",
    module: "messages",
    platform: "tiktok_shop",
    entityType: "conversation",
    description: "Read one conversation, order details, attachments, and relevant after-sales state.",
    requiredInputs: ["shopId", "conversationId"],
    observeInstruction: "Open the requested conversation and locate buyer identity, linked order, message history, attachments, logistics, and after-sales context without sending anything.",
    extractInstruction: "Extract conversation ID, linked order, message timeline, attachments, product facts, logistics facts, after-sales facts, and response deadline.",
    verifyInstruction: "Confirm conversation, buyer, and linked order are consistent and all facts have visible sources and timestamps.",
    outputSchemaKey: "message_thread",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [recordsCaptured("Conversation context")],
  }),
  definition({
    id: "internal.messages.prepare_reply",
    label: "客服意图分类和回复草稿",
    module: "messages",
    platform: "internal",
    executor: "internal",
    riskLevel: "R0_INTERNAL",
    actionType: "INTERNAL_COMPUTE",
    entityType: "conversation",
    description: "Separate verified facts, intent, proposed reply, risk flags, and confidence before any send action.",
    requiredInputs: ["conversationId", "verifiedFacts", "templateVersion"],
    allowedMethods: [],
    observeInstruction: "No browser observation. Use verified conversation, order, logistics, and after-sales facts only.",
    verifyInstruction: "Block unsupported refund, compensation, delivery, or policy promises and return a typed draft with risk classification.",
    outputSchemaKey: "reply_draft",
    postconditions: [recordsCaptured("Customer-service draft")],
  }),
  definition({
    id: "tiktok.messages.send_faq_reply",
    label: "发送低风险客服回复",
    module: "messages",
    platform: "tiktok_shop",
    riskLevel: "R2_REVERSIBLE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "conversation",
    description: "Send one approved low-risk FAQ or factual logistics reply in the correct conversation.",
    requiredInputs: ["shopId", "conversationId", "approvedReply", "replyHash"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Open the requested conversation, confirm buyer/order identity, inspect duplicate history, verify current factual context, and locate the composer.",
    verifyInstruction: "Confirm the exact reply appears once, the conversation is marked replied, and the message persists after refresh.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 60,
  }),
  definition({
    id: "tiktok.messages.send_sensitive_reply",
    label: "发送退款、赔偿或承诺类回复",
    module: "messages",
    platform: "tiktok_shop",
    riskLevel: "R3_SENSITIVE_WRITE",
    actionType: "SEND_MESSAGE",
    entityType: "conversation",
    description: "Send a financially or policy-sensitive reply only under a scoped grant and verified case state.",
    requiredInputs: ["shopId", "conversationId", "approvedReply", "replyHash", "approvalRef"],
    allowedMethods: ["click", "fill", "type", "press"],
    observeInstruction: "Open the requested conversation, confirm buyer/order/case identity, verify the authoritative after-sales state and amount, inspect duplicate history, and locate the composer.",
    verifyInstruction: "Confirm the exact approved reply appears once in the correct conversation and the authoritative case state still supports every promise made.",
    preconditions: [AUTHENTICATED, ACCOUNT_MATCHES, NO_CHALLENGE, TARGET_ENTITY_MATCHES],
    postconditions: [externalStateConfirmed()],
    dailyLimit: 10,
  }),
];

export const automationTaskCatalogById = new Map(
  automationTaskCatalog.map((item) => [item.id, item]),
);

export const currentTaskBindings = Object.freeze({
  "orders:pickup_risk": {
    run: "tiktok.orders.audit_fulfillment",
    send: "tiktok.orders.send_customer_message",
  },
  "orders:shipping_contact": {
    run: "tiktok.orders.read_detail",
    send: "tiktok.orders.send_customer_message",
  },
  "orders:shipping_audit": {
    run: "tiktok.orders.sync",
    send: "tiktok.orders.send_customer_message",
  },
  "aftersales:return_explain": {
    run: "tiktok.aftersales.read_return_tracking",
    send: "tiktok.aftersales.send_message",
  },
  "aftersales:proof_upload": {
    run: "tiktok.aftersales.collect_evidence",
    send: "tiktok.aftersales.prepare_appeal",
  },
  "reviews:bad_review": {
    run: "tiktok.reviews.read_context",
    send: "tiktok.reviews.send_reply",
  },
  "inventory:stock_check": {
    run: "internal.inventory.reconcile",
    send: "tiktok.inventory.prepare_update",
  },
  "inventory:replenishment": {
    run: "hcrd.inventory.sync_in_transit",
    send: "internal.inventory.reconcile",
  },
  "creators:creator_lead": {
    run: "echotik.creators.read_detail",
    send: "internal.creators.prepare_outreach",
  },
});

export function getAutomationDefinition(definitionId) {
  return automationTaskCatalogById.get(definitionId);
}

export function resolveCurrentTaskDefinition(task, operation = "run") {
  const binding = currentTaskBindings[`${task?.module}:${task?.category}`];
  const definitionId = binding?.[operation];
  return definitionId ? getAutomationDefinition(definitionId) : undefined;
}
