export const storeOptions = [
  "美妆小铺-TK001",
  "M店-ST&BW",
  "马尾假发专营",
];

export const tasks = [
  {
    id: "task-order-pickup-risk",
    title: "订单距离24h揽收截止还有1小时23分",
    module: "orders",
    category: "pickup_risk",
    source: "TikTok Shop",
    priority: "urgent",
    shift: "morning",
    dueTime: "10:30",
    dueLabel: "今天 10:30",
    status: "open",
    subject: "订单 5761123456789123456",
    summary: "客户已付款，物流单已出但仓库未上传揽收轨迹。",
    automationAction: "自动催仓库揽收并准备补传物流信息",
    scriptTitle: "物流延迟 / 未揽收安抚话术",
    script:
      "亲爱的，您好！抱歉让您久等了，您的订单物流更新可能有延迟，我们已经催促仓库尽快揽收。预计会在今天内处理，请您放心。给您带来不便非常抱歉，感谢您的理解！",
    details: [
      ["平台订单号", "5789123456789123456"],
      ["买家", "@小丸子不圆"],
      ["店铺", "美妆小铺-TK001"],
      ["物流方式", "J&T Express"],
      ["承诺揽收时效", "2026-07-06 10:30"],
      ["当前状态", "超时风险"],
    ],
  },
  {
    id: "task-order-m-store-contact",
    title: "M店 ST&BW 订单当天联系客户",
    module: "orders",
    category: "shipping_contact",
    source: "M店",
    priority: "high",
    shift: "morning",
    dueTime: "11:00",
    dueLabel: "今天 11:00",
    status: "open",
    subject: "ST&BW 新订单 5768872001",
    summary: "M店客户下单 ST&BW，需要当天联系确认发货预期。",
    automationAction: "自动发送 ST&BW 当天联系消息",
    scriptTitle: "ST&BW 当天联系话术",
    script:
      "亲爱的，您好！我们已经收到您的订单，会尽快为您安排发货。后续物流有更新我们会及时同步，如您有任何问题也可以直接在订单消息里联系我们。",
    details: [
      ["商品", "ST&BW Ponytail 18in"],
      ["店铺", "M店-ST&BW"],
      ["下单时间", "2026-07-06 09:18"],
      ["联系要求", "当天联系"],
    ],
  },
  {
    id: "task-aftersales-return",
    title: "售后申请待解释提醒",
    module: "aftersales",
    category: "return_explain",
    source: "TikTok Shop",
    priority: "high",
    shift: "morning",
    dueTime: "11:30",
    dueLabel: "今天 11:30",
    status: "open",
    subject: "退款退货申请 AF-9021",
    summary: "买家提交退货退款，需要解释流程并提醒按平台步骤寄回。",
    automationAction: "自动发送退货流程提醒并登记售后节点",
    scriptTitle: "待退货解释提醒",
    script:
      "亲爱的，您好！我们已收到您的售后申请。请您按照 TikTok Shop 页面提示完成退货流程，并保留物流凭证。收到退货后我们会按平台规则尽快处理。",
    details: [
      ["售后类型", "退货退款"],
      ["商品", "Ponytail Extension"],
      ["响应期限", "4个工作日内"],
    ],
  },
  {
    id: "task-review-video",
    title: "差评客户是否回复视频证据",
    module: "reviews",
    category: "bad_review",
    source: "Product Ratings",
    priority: "high",
    shift: "morning",
    dueTime: "11:45",
    dueLabel: "今天 11:45",
    status: "processing",
    subject: "1星评价 RV-1882",
    summary: "客户反馈发片脱落，昨天已请求视频证据，上午需要检查是否回复。",
    automationAction: "自动检查客户回复并发送一次视频证据提醒",
    scriptTitle: "索要视频证据话术",
    script:
      "亲爱的，您好！为了更准确地帮您解决问题，方便的话请您上传一段展示问题位置的小视频。我们会根据实际情况尽快协助处理，谢谢您的配合。",
    details: [
      ["评分", "1星"],
      ["问题分类", "产品质量"],
      ["证据状态", "待客户视频"],
    ],
  },
  {
    id: "task-inventory-check",
    title: "惠程荣达库存与 TikTok 库存不一致",
    module: "inventory",
    category: "stock_check",
    source: "系统预警",
    priority: "medium",
    shift: "morning",
    dueTime: "11:50",
    dueLabel: "今天 11:50",
    status: "open",
    subject: "SKU PT-BW-18",
    summary: "惠程荣达实际库存 14，TikTok 可售库存 22，存在超卖风险。",
    automationAction: "自动生成库存调整单并同步待确认队列",
    scriptTitle: "库存核对备注",
    script: "SKU PT-BW-18 惠程荣达实际库存低于 TikTok 可售库存，请先下调平台库存，再核对在途数量。",
    details: [
      ["惠程荣达库存", "14"],
      ["TikTok库存", "22"],
      ["在途数量", "36"],
      ["安全库存", "30"],
    ],
  },
  {
    id: "task-order-second-pickup",
    title: "揽收时效预警二次跟进",
    module: "orders",
    category: "pickup_risk",
    source: "TikTok Shop",
    priority: "high",
    shift: "afternoon",
    dueTime: "15:00",
    dueLabel: "今天 15:00",
    status: "open",
    subject: "订单 5761123456789007781",
    summary: "下午仍未出现揽收轨迹，需要再次联系仓库。",
    automationAction: "自动二次催仓库揽收并校验面单状态",
    scriptTitle: "仓库催揽收备注",
    script: "该订单已接近揽收时效，请优先安排揽收并回传轨迹；如面单异常，请立即反馈。",
    details: [
      ["商品", "Ponytail 22in"],
      ["物流方式", "J&T Express"],
      ["承诺揽收时效", "2026-07-06 15:00"],
    ],
  },
  {
    id: "task-aftersales-proof",
    title: "售后物流凭证待上传",
    module: "aftersales",
    category: "proof_upload",
    source: "TikTok Shop",
    priority: "medium",
    shift: "afternoon",
    dueTime: "15:30",
    dueLabel: "今天 15:30",
    status: "open",
    subject: "争议 DIS-2209",
    summary: "不合理退款争议需要整理物流妥投证明和沟通记录。",
    automationAction: "自动汇总物流凭证、沟通记录和申诉证据包",
    scriptTitle: "申诉证据清单",
    script: "证据建议：妥投截图、物流轨迹、商品页面承诺、客户沟通记录、产品实拍或质检记录。",
    details: [
      ["争议期限", "24小时内提交证据"],
      ["退款金额", "$39.99"],
      ["证据状态", "待整理"],
    ],
  },
  {
    id: "task-review-new",
    title: "下午新增差评处理",
    module: "reviews",
    category: "bad_review",
    source: "Product Ratings",
    priority: "medium",
    shift: "afternoon",
    dueTime: "16:00",
    dueLabel: "今天 16:00",
    status: "open",
    subject: "2星评价 RV-1904",
    summary: "客户反馈颜色与预期不一致，需要合规回复并判断是否索要图片。",
    automationAction: "自动发送差评关怀回复并创建图片证据跟进",
    scriptTitle: "差评回复草稿",
    script:
      "亲爱的，您好！很抱歉这次体验没有达到您的预期。我们重视您的反馈，会根据您描述的问题进一步核查，并尽力为您提供合适的帮助。",
    details: [
      ["评分", "2星"],
      ["问题分类", "颜色/预期差异"],
      ["合规提醒", "不得要求改评或诱导好评"],
    ],
  },
  {
    id: "task-order-audit",
    title: "今日订单发货复核",
    module: "orders",
    category: "shipping_audit",
    source: "系统任务",
    priority: "medium",
    shift: "before_leave",
    dueTime: "18:00",
    dueLabel: "今天 18:00",
    status: "open",
    subject: "今日发货批次",
    summary: "下班前复核面单打印、仓库揽收、异常订单备注。",
    automationAction: "自动跑发货复核：未揽收、未联系、面单异常",
    scriptTitle: "发货复核清单",
    script: "复核：1. 未揽收订单；2. M店 ST&BW 当天联系；3. 面单异常；4. 送达3天真实体验邀请待办。",
    details: [
      ["今日订单", "126"],
      ["未揽收", "18"],
      ["需联系", "7"],
    ],
  },
  {
    id: "task-inventory-replenish",
    title: "备货表完成后核对在途数量",
    module: "inventory",
    category: "replenishment",
    source: "惠程荣达",
    priority: "high",
    shift: "before_leave",
    dueTime: "18:30",
    dueLabel: "今天 18:30",
    status: "open",
    subject: "低库存 SKU 6个",
    summary: "备货表已生成，需要和惠程荣达在途数量核对。",
    automationAction: "自动核对在途数量并生成备货确认单",
    scriptTitle: "备货核对备注",
    script: "请核对低库存 SKU 的实际库存、TikTok 可售库存、在途数量和安全库存，再确认建议备货量。",
    details: [
      ["低库存SKU", "6"],
      ["在途待确认", "4"],
      ["最高风险SKU", "PT-BW-18"],
    ],
  },
  {
    id: "task-creator-pony",
    title: "找马尾方向红人并记录联系方式",
    module: "creators",
    category: "creator_lead",
    source: "人工线索",
    priority: "low",
    shift: "before_leave",
    dueTime: "18:40",
    dueLabel: "今天 18:40",
    status: "open",
    subject: "Ponytail creator leads",
    summary: "整理 ponytail / hair extension / beauty 方向达人公开邮箱。",
    automationAction: "自动抓取公开联系方式并生成低频外联队列",
    scriptTitle: "达人建联邮件草稿",
    script:
      "Hi, we love your hair and beauty content. We are looking for creators to try our ponytail extension products. If you are open to a collaboration, we would be happy to share more details.",
    details: [
      ["关键词", "ponytail, hair extension, beauty"],
      ["联系来源", "主页公开信息"],
      ["外联方式", "邮件草稿"],
    ],
  },
];

export const creatorSearchKeywords = [
  "drawstring ponytail",
  "half wig",
  "wig",
  "crochet hair",
  "braids",
  "black girl",
];

export const creatorFunnelStages = [
  { id: "imported", label: "已导入" },
  { id: "qualified", label: "粗筛通过" },
  { id: "needs_contact", label: "待补联系方式" },
  { id: "ready_to_contact", label: "待联系" },
  { id: "contacted", label: "已联系" },
  { id: "replied", label: "已回复" },
  { id: "sample_sent", label: "已寄样" },
  { id: "published", label: "已发布" },
  { id: "review", label: "复盘" },
];

export const creatorLeads = [
  {
    id: "creator-ari",
    handle: "arihairdaily",
    displayName: "Ari Hair Daily",
    followers: 12400,
    crmStatus: "needs_contact",
    source: "EchoTik CSV 2026-07-06",
    description: "日常发型教程和黑女孩编发内容，视频里经常出现 drawstring ponytail 与 protective style。",
    recommendedProducts: ["Drawstring Ponytail 18in", "Braids Extension Set"],
    matchedKeywords: ["drawstring ponytail", "black girl", "braids"],
    highPerformingCoverUrl:
      "https://images.unsplash.com/photo-1527203561188-dae1bc1a417f?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
    productAssociatedVideos: ["v-ari-1", "v-ari-2", "v-ari-3"],
    contact: {
      email: "",
      instagram: "",
      notes: "主页 Bio 暂未记录联系方式，需人工打开 TikTok 主页确认。",
    },
    recentVideos: [
      {
        id: "v-ari-1",
        title: "Drawstring ponytail refresh for work",
        views: 8200,
        createDate: "2026-06-30",
        coverUrl:
          "https://images.unsplash.com/photo-1527203561188-dae1bc1a417f?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
      },
      { id: "v-ari-2", views: 6100, createDate: "2026-06-27" },
      { id: "v-ari-3", views: 2200, createDate: "2026-06-21" },
      { id: "v-ari-4", views: 1900, createDate: "2026-06-18" },
      { id: "v-ari-5", views: 1500, createDate: "2026-06-15" },
      { id: "v-ari-6", views: 1200, createDate: "2026-06-12" },
      { id: "v-ari-7", views: 980, createDate: "2026-06-08" },
      { id: "v-ari-8", views: 7600, createDate: "2026-06-03" },
      { id: "v-ari-9", views: 540, createDate: "2026-05-28" },
      { id: "v-ari-10", views: 1320, createDate: "2026-05-23" },
    ],
  },
  {
    id: "creator-nia",
    handle: "niawigroom",
    displayName: "Nia Wig Room",
    followers: 8600,
    crmStatus: "qualified",
    source: "EchoTik CSV 2026-07-06",
    description: "以 half wig 和自然蓬松发型转换为主，封面能直接判断产品风格和妆造完成度。",
    recommendedProducts: ["Half Wig Natural Black", "Kinky Straight Wig"],
    matchedKeywords: ["half wig", "wig", "black girl"],
    highPerformingCoverUrl:
      "https://images.unsplash.com/photo-1641522682563-850550dff807?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
    productAssociatedVideos: ["v-nia-1", "v-nia-4"],
    contact: {
      email: "",
      instagram: "niawigroom",
      notes: "IG 已在主页出现，邮箱待确认。",
    },
    recentVideos: [
      {
        id: "v-nia-1",
        title: "Half wig blend test",
        views: 12400,
        createDate: "2026-07-01",
        coverUrl:
          "https://images.unsplash.com/photo-1641522682563-850550dff807?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
      },
      { id: "v-nia-2", views: 4100, createDate: "2026-06-26" },
      { id: "v-nia-3", views: 3900, createDate: "2026-06-22" },
      { id: "v-nia-4", views: 3100, createDate: "2026-06-18" },
      { id: "v-nia-5", views: 2700, createDate: "2026-06-15" },
      { id: "v-nia-6", views: 2600, createDate: "2026-06-12" },
      { id: "v-nia-7", views: 930, createDate: "2026-06-09" },
      { id: "v-nia-8", views: 1400, createDate: "2026-06-04" },
      { id: "v-nia-9", views: 840, createDate: "2026-05-31" },
      { id: "v-nia-10", views: 1660, createDate: "2026-05-25" },
    ],
  },
  {
    id: "creator-kay",
    handle: "kaycrochetstyles",
    displayName: "Kay Crochet Styles",
    followers: 43800,
    crmStatus: "ready_to_contact",
    source: "EchoTik CSV 2026-07-06",
    description: "crochet hair 与 braids 教程播放稳定，适合测试编发类产品和补充发包。",
    recommendedProducts: ["Crochet Hair Bundle", "Pre-stretched Braids"],
    matchedKeywords: ["crochet hair", "braids", "black girl"],
    highPerformingCoverUrl:
      "https://images.unsplash.com/photo-1767249628216-e9e8824f3940?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
    productAssociatedVideos: ["v-kay-1", "v-kay-2", "v-kay-6", "v-kay-9"],
    contact: {
      email: "kaystyles@example.com",
      instagram: "kaycrochetstyles",
      notes: "邮箱来自主页 Bio，待人工二次确认后发送。",
    },
    recentVideos: [
      {
        id: "v-kay-1",
        title: "Fast crochet hair install",
        views: 28800,
        createDate: "2026-07-03",
        coverUrl:
          "https://images.unsplash.com/photo-1767249628216-e9e8824f3940?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
      },
      { id: "v-kay-2", views: 18400, createDate: "2026-06-29" },
      { id: "v-kay-3", views: 15200, createDate: "2026-06-25" },
      { id: "v-kay-4", views: 9800, createDate: "2026-06-22" },
      { id: "v-kay-5", views: 7700, createDate: "2026-06-20" },
      { id: "v-kay-6", views: 6900, createDate: "2026-06-16" },
      { id: "v-kay-7", views: 5300, createDate: "2026-06-11" },
      { id: "v-kay-8", views: 2400, createDate: "2026-06-08" },
      { id: "v-kay-9", views: 2200, createDate: "2026-06-02" },
      { id: "v-kay-10", views: 1800, createDate: "2026-05-29" },
    ],
  },
  {
    id: "creator-maya",
    handle: "mayaponytailfit",
    displayName: "Maya Ponytail Fit",
    followers: 19200,
    crmStatus: "contacted",
    source: "EchoTik CSV 2026-07-06",
    description: "健身和日常出门场景里的 ponytail 内容，适合强调耐用、蓬松和快速佩戴。",
    recommendedProducts: ["Wrap Ponytail 22in", "Drawstring Ponytail 20in"],
    matchedKeywords: ["drawstring ponytail", "wig"],
    highPerformingCoverUrl:
      "https://images.unsplash.com/photo-1653263171267-1cf1776f04d2?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
    productAssociatedVideos: ["v-maya-1"],
    contact: {
      email: "maya.fit@example.com",
      instagram: "",
      notes: "已通过邮箱第一轮联系，等待回复。",
    },
    recentVideos: [
      {
        id: "v-maya-1",
        title: "Ponytail after gym check",
        views: 9400,
        createDate: "2026-06-28",
        coverUrl:
          "https://images.unsplash.com/photo-1653263171267-1cf1776f04d2?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
      },
      { id: "v-maya-2", views: 6100, createDate: "2026-06-24" },
      { id: "v-maya-3", views: 5200, createDate: "2026-06-20" },
      { id: "v-maya-4", views: 4300, createDate: "2026-06-17" },
      { id: "v-maya-5", views: 3900, createDate: "2026-06-13" },
      { id: "v-maya-6", views: 1400, createDate: "2026-06-10" },
      { id: "v-maya-7", views: 880, createDate: "2026-06-07" },
      { id: "v-maya-8", views: 720, createDate: "2026-06-04" },
      { id: "v-maya-9", views: 2600, createDate: "2026-05-30" },
      { id: "v-maya-10", views: 1180, createDate: "2026-05-26" },
    ],
  },
  {
    id: "creator-tee",
    handle: "teebraidslab",
    displayName: "Tee Braids Lab",
    followers: 67500,
    crmStatus: "sample_sent",
    source: "EchoTik CSV 2026-07-06",
    description: "编发过程和成品展示都很强，适合作为样品合作候选，已进入寄样跟进。",
    recommendedProducts: ["Pre-stretched Braids", "Crochet Hair Bundle"],
    matchedKeywords: ["braids", "crochet hair", "black girl"],
    highPerformingCoverUrl:
      "https://images.unsplash.com/photo-1763256433460-e994fe2c28da?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
    productAssociatedVideos: ["v-tee-1", "v-tee-2", "v-tee-3", "v-tee-4"],
    contact: {
      email: "teamtee@example.com",
      instagram: "teebraidslab",
      notes: "7月5日已寄样，等对方确认拍摄时间。",
    },
    recentVideos: [
      {
        id: "v-tee-1",
        title: "Braids install day",
        views: 40200,
        createDate: "2026-07-02",
        coverUrl:
          "https://images.unsplash.com/photo-1763256433460-e994fe2c28da?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
      },
      { id: "v-tee-2", views: 24400, createDate: "2026-06-30" },
      { id: "v-tee-3", views: 21000, createDate: "2026-06-25" },
      { id: "v-tee-4", views: 18800, createDate: "2026-06-23" },
      { id: "v-tee-5", views: 12100, createDate: "2026-06-19" },
      { id: "v-tee-6", views: 8400, createDate: "2026-06-16" },
      { id: "v-tee-7", views: 7300, createDate: "2026-06-12" },
      { id: "v-tee-8", views: 3900, createDate: "2026-06-07" },
      { id: "v-tee-9", views: 2500, createDate: "2026-06-02" },
      { id: "v-tee-10", views: 1880, createDate: "2026-05-30" },
    ],
  },
  {
    id: "creator-zora",
    handle: "zorawigtryons",
    displayName: "Zora Wig Try-ons",
    followers: 29500,
    crmStatus: "published",
    source: "EchoTik CSV 2026-07-06",
    description: "wig try-on 视频已经发布过类似商品，适合进入复盘，后续看 GMV 与评论反馈。",
    recommendedProducts: ["Kinky Straight Wig", "Half Wig Natural Black"],
    matchedKeywords: ["wig", "half wig", "black girl"],
    highPerformingCoverUrl:
      "https://images.unsplash.com/photo-1474648676916-0558486e7fa0?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
    productAssociatedVideos: ["v-zora-1", "v-zora-2"],
    contact: {
      email: "zora.tryons@example.com",
      instagram: "zorawigtryons",
      notes: "已发布第一条，待记录播放、点击和评论质量。",
    },
    recentVideos: [
      {
        id: "v-zora-1",
        title: "Half wig try-on review",
        views: 18200,
        createDate: "2026-07-04",
        coverUrl:
          "https://images.unsplash.com/photo-1474648676916-0558486e7fa0?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
      },
      { id: "v-zora-2", views: 9100, createDate: "2026-07-01" },
      { id: "v-zora-3", views: 4400, createDate: "2026-06-26" },
      { id: "v-zora-4", views: 3300, createDate: "2026-06-21" },
      { id: "v-zora-5", views: 3100, createDate: "2026-06-18" },
      { id: "v-zora-6", views: 2890, createDate: "2026-06-14" },
      { id: "v-zora-7", views: 920, createDate: "2026-06-10" },
      { id: "v-zora-8", views: 1260, createDate: "2026-06-05" },
      { id: "v-zora-9", views: 1130, createDate: "2026-06-01" },
      { id: "v-zora-10", views: 980, createDate: "2026-05-27" },
    ],
  },
  {
    id: "creator-lana",
    handle: "lanabeautyfinds",
    displayName: "Lana Beauty Finds",
    followers: 15400,
    crmStatus: "imported",
    source: "EchoTik CSV 2026-07-06",
    description: "beauty 内容不错，但最近没有商品关联视频，先保留为待复核候选。",
    recommendedProducts: ["Drawstring Ponytail 18in"],
    matchedKeywords: ["wig"],
    highPerformingCoverUrl:
      "https://images.unsplash.com/photo-1543366749-f3000e798cbc?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
    productAssociatedVideos: [],
    contact: {
      email: "",
      instagram: "",
      notes: "缺商品关联视频，需要人工判断是否值得补联系方式。",
    },
    recentVideos: [
      {
        id: "v-lana-1",
        title: "Beauty finds haul",
        views: 7200,
        createDate: "2026-06-29",
        coverUrl:
          "https://images.unsplash.com/photo-1543366749-f3000e798cbc?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=900",
      },
      { id: "v-lana-2", views: 4200, createDate: "2026-06-20" },
      { id: "v-lana-3", views: 3100, createDate: "2026-06-11" },
      { id: "v-lana-4", views: 1900, createDate: "2026-06-02" },
      { id: "v-lana-5", views: 1700, createDate: "2026-05-23" },
      { id: "v-lana-6", views: 1600, createDate: "2026-05-16" },
      { id: "v-lana-7", views: 880, createDate: "2026-05-09" },
      { id: "v-lana-8", views: 740, createDate: "2026-05-02" },
      { id: "v-lana-9", views: 410, createDate: "2026-04-24" },
      { id: "v-lana-10", views: 390, createDate: "2026-04-18" },
    ],
  },
];

export const automationEvents = [
  { id: "n8n-morning", label: "上班库存核对", status: "ready", time: "09:00" },
  { id: "n8n-afternoon-review", label: "下午评价检查", status: "ready", time: "15:30" },
  { id: "n8n-evening-stock", label: "下班库存复核", status: "waiting", time: "18:30" },
];

export const apiLanes = [
  {
    title: "MockAdapter",
    description: "当前前端使用，保证页面和规则先跑起来。",
  },
  {
    title: "CsvImportAdapter",
    description: "承接 TikTok 与惠程荣达导出的 CSV/Excel。",
  },
  {
    title: "TikTokShopAdapter",
    description: "后续接 Partner Center 授权、订单、售后、评价等接口。",
  },
  {
    title: "HcrdAdapter",
    description: "优先确认库存 API；拿不到接口时长期走导入兜底。",
  },
];
